"""add role to user model

Revision ID: 124eabc3e3d8
Revises: 7a28645fe622
Create Date: 2025-03-19 13:59:34.375993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models.user_role import UserRole

# revision identifiers, used by Alembic.
revision: str = '124eabc3e3d8'
down_revision: Union[str, None] = '7a28645fe622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default=UserRole.get_default()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
