"""rename checkpoint model as activity

Revision ID: 3278cd6055a5
Revises: 160898e2a8ed
Create Date: 2025-03-15 04:13:54.496604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3278cd6055a5'
down_revision: Union[str, None] = '160898e2a8ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('travel_plan_day_id', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('activity', sa.Text(), nullable=True),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.Column('start_at', sa.Time(), nullable=True),
    sa.Column('end_at', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['travel_plan_day_id'], ['travel_plan_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('checkpoints')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('travel_plan_day_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('activity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tips', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_at', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_at', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['travel_plan_day_id'], ['travel_plan_days.id'], name='checkpoints_travel_plan_day_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='checkpoints_pkey')
    )
    op.drop_table('activities')
    # ### end Alembic commands ###
